/**
 * OSINT Practice Lab Tool Definitions & Execution Metadata
 */

const toolDefinitions = {
    // ==========================================
    // 1. NATIVE CORE TOOLS
    // ==========================================
    whois: {
        id: "whois",
        name: "WHOIS",
        command: "whois",
        executionType: "native",
        category: "Domain Intelligence",
        targetType: "domain",
        description: "Live domain registration and registrar query",
    },
    nslookup: {
        id: "nslookup",
        name: "nslookup",
        command: "nslookup",
        executionType: "native",
        category: "DNS Intelligence",
        targetType: "domainOrIp",
        description: "Authoritative and recursive DNS interrogation",
    },
    dns: {
        id: "dns",
        name: "DNS Lookup",
        command: "dns",
        executionType: "native",
        category: "DNS Intelligence",
        targetType: "domain",
        description: "Multi-record DNS lookup engine",
    },

    // ==========================================
    // 2. CONTAINERIZED CLI TOOLS
    // ==========================================
    dig: {
        id: "dig",
        name: "dig",
        command: "dig",
        executionType: "container",
        binary: "dig",
        category: "DNS Intelligence",
        targetType: "domainOrIp",
        args: (target) => [target, "ANY", "+nocmd", "+stats"],
        timeoutMs: 10000,
        description: "Domain Information Groper DNS interrogation",
    },
    dnsrecon: {
        id: "dnsrecon",
        name: "dnsrecon",
        command: "dnsrecon",
        executionType: "container",
        binary: "dnsrecon",
        category: "DNS Intelligence",
        targetType: "domain",
        args: (target) => ["-d", target],
        timeoutMs: 15000,
        description: "DNS zone enumeration and discovery tool",
    },
    dnsenum: {
        id: "dnsenum",
        name: "dnsenum",
        command: "dnsenum",
        executionType: "container",
        binary: "dnsenum",
        category: "DNS Intelligence",
        targetType: "domain",
        args: (target) => ["--noreverse", target],
        timeoutMs: 15000,
        description: "DNS enumeration and zone scripter",
    },
    fierce: {
        id: "fierce",
        name: "Fierce",
        command: "fierce",
        executionType: "container",
        binary: "fierce",
        category: "DNS Intelligence",
        targetType: "domain",
        args: (target) => ["--domain", target],
        timeoutMs: 15000,
        description: "Subdomain and IP space reconnaissance scanner",
    },
    subfinder: {
        id: "subfinder",
        name: "Subfinder",
        command: "subfinder",
        executionType: "container",
        binary: "subfinder",
        category: "Subdomain Enumeration",
        targetType: "domain",
        args: (target) => ["-d", target, "-silent"],
        timeoutMs: 15000,
        description: "Fast passive subdomain discovery engine",
    },
    amass: {
        id: "amass",
        name: "Amass",
        command: "amass",
        executionType: "container",
        binary: "amass",
        category: "Subdomain Enumeration",
        targetType: "domain",
        args: (target) => ["enum", "-passive", "-d", target],
        timeoutMs: 20000,
        description: "OWASP Attack Surface and Asset Discovery",
    },
    assetfinder: {
        id: "assetfinder",
        name: "Assetfinder",
        command: "assetfinder",
        executionType: "container",
        binary: "assetfinder",
        category: "Subdomain Enumeration",
        targetType: "domain",
        args: (target) => ["--subs-only", target],
        timeoutMs: 15000,
        description: "Find related domains and subdomains",
    },
    sherlock: {
        id: "sherlock",
        name: "Sherlock",
        command: "sherlock",
        executionType: "container",
        binary: "sherlock",
        category: "Username Investigation",
        targetType: "username",
        args: (target) => [target, "--print-found", "--timeout", "10"],
        timeoutMs: 20000,
        description: "Cross-platform social media account hunter",
    },
    maigret: {
        id: "maigret",
        name: "Maigret",
        command: "maigret",
        executionType: "container",
        binary: "maigret",
        category: "Username Investigation",
        targetType: "username",
        args: (target) => [target, "--timeout", "10"],
        timeoutMs: 20000,
        description: "Deep username dossier and presence mapper",
    },
    theharvester: {
        id: "theharvester",
        name: "theHarvester",
        command: "theharvester",
        executionType: "container",
        binary: "theHarvester",
        category: "Email Investigation",
        targetType: "domain",
        args: (target) => ["-d", target, "-b", "all", "-l", "50"],
        timeoutMs: 20000,
        description: "E-mail, subdomain, and employee harvester",
    },
    holehe: {
        id: "holehe",
        name: "Holehe",
        command: "holehe",
        executionType: "container",
        binary: "holehe",
        category: "Email Investigation",
        targetType: "email",
        args: (target) => [target, "--only-used"],
        timeoutMs: 20000,
        description: "Email password-reset account registration probe",
    },
    phoneinfoga: {
        id: "phoneinfoga",
        name: "PhoneInfoga",
        command: "phoneinfoga",
        executionType: "container",
        binary: "phoneinfoga",
        category: "Phone Investigation",
        targetType: "phone",
        args: (target) => ["scan", "-n", target],
        timeoutMs: 15000,
        description: "International phone number and telecom scanner",
    },
    exiftool: {
        id: "exiftool",
        name: "ExifTool",
        command: "exiftool",
        executionType: "container",
        binary: "exiftool",
        category: "Metadata Investigation",
        targetType: "filePath",
        args: (target) => ["-j", target],
        timeoutMs: 10000,
        description: "Read and write file metadata and EXIF tags",
    },
    whatweb: {
        id: "whatweb",
        name: "WhatWeb",
        command: "whatweb",
        executionType: "container",
        binary: "whatweb",
        category: "Web Reconnaissance",
        targetType: "domainOrIp",
        args: (target) => ["--color=never", target],
        timeoutMs: 15000,
        description: "Next generation web scanner and technology profiler",
    },
    nmap: {
        id: "nmap",
        name: "Nmap",
        command: "nmap",
        executionType: "container",
        binary: "nmap",
        category: "Network Intelligence",
        targetType: "domainOrIp",
        args: (target) => ["-F", "-T4", target],
        timeoutMs: 30000,
        description: "Network exploration tool and port scanner",
    },
    spiderfoot: {
        id: "spiderfoot",
        name: "SpiderFoot",
        command: "spiderfoot",
        executionType: "container",
        binary: "sf",
        category: "Reconnaissance Engine",
        targetType: "domainOrIp",
        args: (target) => ["-s", target, "-u", "cli"],
        timeoutMs: 30000,
        description: "Automated OSINT intelligence gathering framework",
    },

    // ==========================================
    // 3. API-BASED TOOLS
    // ==========================================
    hunter: {
        id: "hunter",
        name: "Hunter.io",
        command: "hunter",
        executionType: "api",
        requiredEnv: "HUNTER_API_KEY",
        category: "Email Investigation",
        targetType: "domain",
        description: "Corporate email pattern and domain search API",
    },
    shodan: {
        id: "shodan",
        name: "Shodan",
        command: "shodan",
        executionType: "api",
        requiredEnv: "SHODAN_API_KEY",
        category: "Threat Intelligence",
        targetType: "domainOrIp",
        description: "Search engine for Internet-connected devices",
    },
    censys: {
        id: "censys",
        name: "Censys",
        command: "censys",
        executionType: "api",
        requiredEnv: "CENSYS_API_ID",
        category: "Threat Intelligence",
        targetType: "domainOrIp",
        description: "Attack surface management and host search API",
    },
    securitytrails: {
        id: "securitytrails",
        name: "SecurityTrails",
        command: "securitytrails",
        executionType: "api",
        requiredEnv: "SECURITYTRAILS_API_KEY",
        category: "DNS Intelligence",
        targetType: "domain",
        description: "Total domain and DNS history intelligence API",
    },
    virustotal: {
        id: "virustotal",
        name: "VirusTotal",
        command: "virustotal",
        executionType: "api",
        requiredEnv: "VIRUSTOTAL_API_KEY",
        category: "Threat Intelligence",
        targetType: "domainOrIp",
        description: "Multi-antivirus threat and reputation intelligence",
    },
    hibp: {
        id: "hibp",
        name: "Have I Been Pwned",
        command: "hibp",
        executionType: "api",
        requiredEnv: "HIBP_API_KEY",
        category: "Threat Intelligence",
        targetType: "email",
        description: "Data breach exposure query API",
    },

    // ==========================================
    // 4. WEB / PUBLIC SERVICES
    // ==========================================
    crtsh: {
        id: "crtsh",
        name: "crt.sh",
        command: "crtsh",
        executionType: "web",
        category: "Subdomain Enumeration",
        targetType: "domain",
        description: "Public Certificate Transparency log search",
    },
    urlscan: {
        id: "urlscan",
        name: "URLScan.io",
        command: "urlscan",
        executionType: "web",
        category: "Web Reconnaissance",
        targetType: "domain",
        description: "Free URL and website intelligence sandbox",
    },
    wayback: {
        id: "wayback",
        name: "Wayback Machine",
        command: "wayback",
        executionType: "web",
        category: "History & Archives",
        targetType: "domain",
        description: "Internet Archive historical snapshot CDX index",
    },
    dnsdumpster: {
        id: "dnsdumpster",
        name: "DNSDumpster",
        command: "dnsdumpster",
        executionType: "web",
        category: "DNS Intelligence",
        targetType: "domain",
        description: "DNS reconnaissance and map search engine",
    },
    whatsmyname: {
        id: "whatsmyname",
        name: "WhatsMyName",
        command: "whatsmyname",
        executionType: "web",
        category: "Username Investigation",
        targetType: "username",
        description: "User account reconnaissance across public platforms",
    },
    wappalyzer: {
        id: "wappalyzer",
        name: "Wappalyzer",
        command: "wappalyzer",
        executionType: "web",
        category: "Web Reconnaissance",
        targetType: "domain",
        description: "Web application technology and framework scanner",
    },
    duckduckgo: {
        id: "duckduckgo",
        name: "DuckDuckGo",
        command: "duckduckgo",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Instant answer and privacy search discovery",
    },
    brave: {
        id: "brave",
        name: "Brave Search",
        command: "brave",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Independent web crawler and search index",
    },
    mojeek: {
        id: "mojeek",
        name: "Mojeek",
        command: "mojeek",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Non-tracking independent search crawler",
    },
    google: {
        id: "google",
        name: "Google",
        command: "google",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Google search intelligence index",
    },
    bing: {
        id: "bing",
        name: "Bing",
        command: "bing",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Microsoft Bing search web index",
    },
    yandex: {
        id: "yandex",
        name: "Yandex",
        command: "yandex",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Yandex global web search discovery",
    },
    dork: {
        id: "dork",
        name: "Google Dorking",
        command: "dork",
        executionType: "web",
        category: "Search Investigation",
        targetType: "dork",
        description: "Advanced Google search operator query parser",
    },
    lens: {
        id: "lens",
        name: "Google Lens",
        command: "lens",
        executionType: "web",
        category: "Search Investigation",
        targetType: "url",
        description: "Visual reverse image asset analysis",
    },
};

module.exports = toolDefinitions;
